version: '3.8'

services:
  facebook-reports:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facebook-reports-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      
      # Facebook API
      - FACEBOOK_ACCESS_TOKEN=${FACEBOOK_ACCESS_TOKEN}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      
      # Google Ads API
      - GOOGLE_ADS_DEVELOPER_TOKEN=${GOOGLE_ADS_DEVELOPER_TOKEN}
      - GOOGLE_ADS_CLIENT_ID=${GOOGLE_ADS_CLIENT_ID}
      - GOOGLE_ADS_CLIENT_SECRET=${GOOGLE_ADS_CLIENT_SECRET}
      - GOOGLE_ADS_REFRESH_TOKEN=${GOOGLE_ADS_REFRESH_TOKEN}
      - GOOGLE_ADS_LOGIN_CUSTOMER_ID=${GOOGLE_ADS_LOGIN_CUSTOMER_ID}
      
      # Application Settings
      - WEB_HOST=0.0.0.0
      - WEB_PORT=5000
      - DEBUG=false
      - TOKEN_RENEWAL_DAYS=50
      - TOKEN_CHECK_INTERVAL=86400
      
      # Optional: Enable daily cron job
      - ENABLE_CRON=false
      - DAILY_UPDATE_HOUR=6
    
    volumes:
      - ./logs:/app/logs
      - ./backup:/app/backup
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: facebook-reports-network
